<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1585571426474' stop='1585571550567'>
    <name>First tests pull</name>
    <title>First tests pull</title>
    <test-cases>
        <test-case start='1585571426475' status='passed' stop='1585571442649'>
            <name>Login in Yandex.Mail</name>
            <title>Login in Yandex.Mail</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1585571442650' status='passed' stop='1585571448249'>
            <name>Log out Yandex.Mail</name>
            <title>Log out Yandex.Mail</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1585571448249' status='failed' stop='1585571550535'>
            <name>Incorrect password</name>
            <title>Incorrect password</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:38:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585571550535' status='failed' stop='1585571550548'>
            <name>Incorrect login</name>
            <title>Incorrect login</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:11:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585571550548' status='failed' stop='1585571550556'>
            <name>Navigation</name>
            <title>Navigation</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:11:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585571550556' status='failed' stop='1585571550565'>
            <name>Change language</name>
            <title>Change language</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59087
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:11:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\firstPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>